# Generated by Django 5.2.7 on 2025-10-21 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Pergunta')),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='F', max_length=1, verbose_name='Dificuldade')),
                ('categoria', models.CharField(default='Geral', max_length=100, verbose_name='Categoria')),
                ('tempo_limite', models.IntegerField(default=30, help_text='Tempo em segundos para responder (ex: 30s)', verbose_name='Tempo Limite')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Resposta')),
                ('is_correta', models.BooleanField(default=False, verbose_name='É a Resposta Correta?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.pergunta', verbose_name='Pergunta Relacionada')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
