# Generated by Django 5.2.7 on 2025-10-27 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_totais', models.IntegerField(default=0)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='F', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pontuação do Usuário',
                'verbose_name_plural': 'Pontuações dos Usuários',
            },
        ),
    ]
