# Generated by Django 5.2.7 on 2025-10-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_pontuacao_total_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.png', null=True, upload_to='fotos_perfil/'),
        ),
    ]
